[http.middlewares.simpleAuth.basicAuth]
  users = [
    "nick:$apr1$asdasdsadasfasdasdasda"
  ]

[http.routers.api]
  rule = "Host(`monitor.yourdomain.com`)"
  entrypoints = ["websecure"]
  middlewares = ["simpleAuth"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
